name: ycb_slide
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
- matplotlib=3.5.1
- pip=21.2.4
- pyvista=0.34.0
- tqdm=4.64.0
- pip:
  - matplotlib-inline==0.1.3
  - open3d
  - opencv-python
  - pandas==1.4.2
  - gitpython==3.1.27
  - digit-interface==0.2.1
  - gdown==4.5.1
  - dill==0.3.4
  - pillow==9.2.0